spring/golf/trunk/src/main/java/joejava/golf/domain/Course.java
package joejava.golf.domain;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;

@Entity
public class Course {
	@Id
	@GeneratedValue
	private Integer id;
	
	private String name;
	
	@Column(unique=true)
	private String code;
	
	private String phoneNumber;
	
	@OneToOne(cascade=CascadeType.ALL)
	private Address address;
	
	@OneToMany(cascade=CascadeType.ALL, mappedBy="course", orphanRemoval=true)
	private Set<Tee> tee = new HashSet<Tee>();

	public Course(){}
	
	@Override
	public String toString() {
		return "Course [address=" + address + ", code=" + code + ", id=" + id
				+ ", name=" + name + ", phoneNumber=" + phoneNumber + ", tee="
				+ tee + "]";
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Address getAddress() {
		return address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public Set<Tee> getTee() {
		return tee;
	}

	public void setTee(Set<Tee> tee) {
		this.tee = tee;
	}

	public String getPhoneNumber() {
		return phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getCode() {
		return code;
	}
}

spring/golf/trunk/src/main/java/joejava/golf/domain/Round.java
package joejava.golf.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import joejava.golf.util.GolfConstants;
@Entity
public class Round {
	@Id
	@GeneratedValue
	private Integer id;

	@ManyToOne
	private Golfer golfer;
	
	@ManyToOne(optional=false)
	private Tee tee;
	
	@OneToMany(cascade={CascadeType.ALL}, mappedBy="round", orphanRemoval=true)
	private List<Score> score = new ArrayList<Score>();

	@Temporal(TemporalType.TIMESTAMP)
	private Date roundDate;
	
	public Round(){}

	public Round(Tee tee, List<Score> score){
		this.tee = tee;
		this.score = score;
	}

	@Transient
	public Integer getScoreTotal(){
		int total = 0;
		for(Score s : this.score){
			total += s.getScore();
		}
		
		return total;
	}
	
	@Transient
	public Integer getScoreOut(){
		int out = 0;
		for(Score s : this.score){
			if(s.getHole().getHoleNo() < 10){
				out += s.getScore();
			}
		}
		
		return out;
	}
	
	@Transient
	public Integer getScoreIn(){
		int in = 0;
		for(Score s : this.score){
			if(s.getHole().getHoleNo() > 9){
				in += s.getScore();
			}
		}		
		
		return in;
	}
	
	@Transient
	public Integer getScoreByPar(){
		return this.getScoreTotal() - this.getTee().getPar();
	}
	
	@Transient
	public Double getDifferential(){
		double diff = (this.getScoreTotal() - this.getTee().getRating()) * (GolfConstants.SLOPE_NUMERATOR/this.getTee().getSlope()); 
		return diff;
	}
	
	@Override
	public String toString() {
		return "Round [id=" + id + "score=" + this.getScoreTotal() + "]";
	}

	public Golfer getGolfer() {
		return golfer;
	}

	public void setGolfer(Golfer golfer) {
		this.golfer = golfer;
	}

	public List<Score> getScore() {
		return score;
	}

	public void setScore(List<Score> score) {
		this.score = score;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Tee getTee() {
		return tee;
	}

	public void setTee(Tee tee) {
		this.tee = tee;
	}

	public List<Score> getScores() {
		return score;
	}

	public void setScores(List<Score> score) {
		this.score = score;
	}

	public Date getRoundDate() {
		return roundDate;
	}

	public void setRoundDate(Date roundDate) {
		this.roundDate = roundDate;
	}
}

spring/golf/trunk/src/main/java/joejava/golf/web/CourseController.java
package joejava.golf.web;

import java.io.IOException;
import java.util.List;
import java.util.Map;

import joejava.golf.domain.Course;
import joejava.golf.service.CourseService;
import joejava.golf.service.UploadService;

import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.multipart.MultipartFile;

@Controller
@RequestMapping("/course")
public class CourseController {

	Logger log = Logger.getLogger(this.getClass());
	
	@Autowired
	private CourseService courseService;
	
	@Autowired
	private UploadService uploadService;	

	@RequestMapping("/list")
	public String listCourses(Map<String, Object> map) {
		log.info("Listing courses");
		List<Course> courses = courseService.listCourse();
		log.info(courses.size());

		map.put("course", new Course());
		map.put("courseList", courses);
		return "course/list";
	}

	@RequestMapping("/{id}")
	public String getCourse(@PathVariable("id") Integer courseId,Map<String, Object> map) {
		Course course = courseService.findCourseById(courseId);
		map.put("course",course);
		return "course/show";
	}
	
	//ALWAYS redirect after DELETES/UPDATES
	@RequestMapping(value = "/add", method = RequestMethod.POST)
	public String addCourse(@ModelAttribute("course") Course course, BindingResult result) {
		System.out.println("Adding via web");
		courseService.addCourse(course);
		return "redirect:/course/list";
	}

	@RequestMapping(value = "/add/xml", method = RequestMethod.POST)
	public void addCourse(@RequestBody Course course) {
		System.out.println("Adding via REST POST");
		System.out.println(course.toString());
		courseService.addCourse(course);
	}	
	
	@RequestMapping("/delete/{id}")
	public String deleteCourse(@PathVariable("id")	Integer courseId) {
		courseService.deleteCourse(courseService.findCourseById(courseId));
		return "redirect:/course/list";
	}
	
	@RequestMapping(value = "/upload", method = RequestMethod.POST)
	public String addCourse(@RequestParam("course") MultipartFile file) throws IOException, Exception{
		uploadService.convertDelimitedListToCourseList(file.getInputStream(), ",");
		return "redirect:/course/list";
	}
	
	@RequestMapping(value = "/tee/upload", method = RequestMethod.POST)
	public String addTee(@RequestParam("tee") MultipartFile file) throws IOException, Exception{
		uploadService.convertDelimitedListToTeeList(file.getInputStream(), ",");
		return "redirect:/course/list";
	}	
}

spring/golf/trunk/src/main/webapp/WEB-INF/jsp/course/list.jsp
<%@taglib uri="http://www.springframework.org/tags" prefix="spring"%>
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>

<html>
<head>
	<title>Upload your CSV file of courses</title>
	<style type="text/css" media="screen">
		@import url("/golf/css/styles.css");
    </style>
</head>
<body>

	<h2>Add Course</h2>

	<!-- use href for add just like delete below? -->
	<form:form method="post" action="add" commandName="course">
	
		<table>
		<tr>
			<td><form:label path="name">Name</form:label></td>
			<td><form:input path="name" /></td> 
		</tr>
		<tr>
			<td><form:label path="code">Code</form:label></td>
			<td><form:input path="code" /></td> 
		</tr>
		<tr>
			<td><form:label path="phoneNumber">Phone Number</form:label></td>
			<td><form:input path="phoneNumber" /></td> 
		</tr>
		<tr>
			<td><form:label path="address.street">Street</form:label></td>
			<td><form:input path="address.street" /></td> 
		</tr>
		<tr>
			<td><form:label path="address.city">City</form:label></td>
			<td><form:input path="address.city" /></td> 
		</tr>
		<tr>
			<td><form:label path="address.stateProv">State/Prov.</form:label></td>
			<td><form:input path="address.stateProv" /></td> 
		</tr>
		<tr>
			<td><form:label path="address.zip">Zip</form:label></td>
			<td><form:input path="address.zip" /></td> 
		</tr>				
		<tr>
			<td colspan="2">
				<input type="submit" value="Add Course"/>
			</td>
		</tr>
	</table>	
	</form:form>	

	<h2>Upload Course</h2>
	<form method="post" action="upload" enctype="multipart/form-data">
		<input type="file" name="course"/>
		<input type="submit" name="button" value="Upload"/>		
	</form>

	<h2>Upload Tee</h2>
	<form method="post" action="tee/upload" enctype="multipart/form-data">
		<input type="file" name="tee"/>
		<input type="submit" name="button" value="Upload"/>		
	</form>
	
	<h3>Courses</h3>
	<c:if  test="${!empty courseList}">
	<table class="data">
	<tr>
		<th>Id</th>
		<th>Code</th>
		<th>Name</th>
		<th>Phone</th>
		<th>&nbsp;</th>
	</tr>
	<c:forEach items="${courseList}" var="course">
		<tr>
			<td>${course.id}</td>
			<td>${course.code}</td>
			<td>${course.name }</td>
			<td>${course.phoneNumber }</td>
			<td><a href="delete/${course.id}">delete</a></td>
		</tr>
		
		<c:if test="${!empty course.tee }">
		<tr>
			<table class="data">
				<tr>
					<th>Id</th>
					<th>Tee</th>
					<th>Slope</th>
					<th>Rating</th>
					<th>&nbsp;</th>
				</tr>		
			<c:forEach items="${course.tee}" var="tee">
				<tr>
					<td>${tee.id}</td>
					<td>${tee.name }</td>
					<td>${tee.slope}</td>
					<td>${tee.rating}</td>
					<td><a href="delete/${tee.id}">delete</a></td>
				</tr>
			</c:forEach>
			</table>
		</tr>
		</c:if>
	</c:forEach>
	</table>
	</c:if>	
</body>
</html>

spring/golf/trunk/src/main/webapp/WEB-INF/jsp/course/show.jsp
<%@taglib uri="http://www.springframework.org/tags" prefix="spring"%>
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<html>
<head>
	<title>Golf!</title>
	<style type="text/css" media="screen">
		@import url("/golf/css/styles.css");
    </style>
</head>
<body>

<h2>Show Course</h2>

	<c:if  test="${!empty course}">
	<table class="data">
		<tr>
			<th>Id</th>
			<th>Code</th>
			<th>Name</th>
			<th>Phone</th>
			<th>Address</th>
			<th>&nbsp;</th>
		</tr>
		<tr>
			<td>${course.id }</td>
			<td>${course.code }</td>
			<td>${course.name }</td>
			<td>${course.phone }</td>
			<td>${course.address }</td>
			<td><a href="delete/${course.id}">delete</a></td>
		</tr>
	</table>
	</c:if>

<!-- 
	<h2>Upload Tees</h2>
	<form method="post" action="/golf/course/tee/${golfer.id}/round/upload" enctype="multipart/form-data">
		<input type="file" name="round"/>
		<input type="submit" name="button" value="Upload"/>
	</form>
 -->

	<h3>Tees</h3>
	<c:if  test="${!empty golfer.round}">
	<table class="data">
		<tr>
			<th>Course</th>
			<th>Tee</th>
			<th>Score</th>
			<th>&nbsp;</th>
		</tr>
		<c:forEach items="${golfer.round}" var="round">
			<tr>
				<td>${round.tee.course.name }</td>
				<td>${round.tee.name }</td>
				<td>${round.scoreTotal }</td>
				<td><a href="delete/${round.id}">delete</a></td>
			</tr>
		</c:forEach>
	</table>
	</c:if>	

</body>
</html>